# Generated by Django 4.2 on 2023-10-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_usertable_address_alter_usertable_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_modified',
        ),
    ]
