# Generated by Django 4.2 on 2023-10-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_remove_blog_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
